[package]
name = "circles"
version = "0.1.0"
authors = ["James Baum <james@jamestease.co.uk>"]

[dependencies]
png = "0.11"
cairo-rs = { version = "0.3", features = ["png"] }
rand = "0.4"
nalgebra = "0.14"